### ISSUE TITLE
PythonProDataScience_Ukol1

### ISSUE THREAD

**Issue by Verutynka** [Verutynka/PythonProDataScience_Ukol#1]
@vaclavcepelak

**Comment by vaclavcepelak** [comment]
Ahoj Veroniko,

posílám zpětnou vazbu k úkolu. Poradila sis s tím skvěle! Velmi cením, že ses pustila do bonusu 3, což si nikdo další z "mé" skupiny (zatím) netroufl. V rámci toho, co jsme se na kurzu učili, je úkol splněn, mám k tomu pár poznámek, které ber spíš jako "rady do života":

- Základní rada je si udělat co nejvíc grafů: distribuce hodnot (`sns.histplot(data["Y"], kde=True)`), distribuce reziduí (`sns.histplot(result.resid, kde=True)`), regresní graf predikovaných a skutečných hodnot (`sns.regplot(data, x="Predicted_Y", y="Y")`) - ten ti ukáže, že tam je pár odlehlých pozorování, která jsou extrémně vlivná. Z těch grafů většinou dokážeš odhalit, že v datech je něco nečekaného - nějaký problém, který je třeba řešit. Obecně tady máme málo dat s "nenormální" distribucí, takže ten model je pak hodně nestabilní a s jakoukoliv změnou všechno strašně lítá. (Myslím, že je to trochu nešťastně vybraný úkol, ale zas aspoň vidíš, že v životě nepracuješ jen s hezkými daty.)
Ten problém se ukazuje i v nenormalitě reziduí (Jarque-Beta test - bylo to v lekci 6)

Bonus 3: 
- Vytvořila sis druhý DataFrame a v té formuli micháš dva různé dataframy, což je dost nešťastné, protože jakmile použiješ ten model na jiná data, nejspíš se ti to rozbije. Bylo dobře použít fukci `pd.concat` a ty dva dataframy si spojit
- Existuje ještě jeden výrazně jednodušší způsob (upozorňoval jsem na něj Jirku, aby to přidal do materiálů, ale nevím, jestli to udělal). Ta formula totiž umí pracovat i s kategorickými proměnnými a udělá práci za tebe. Nemusíš tedy vůbec používat `pd.get_dummies`, ale stačí použít `data`, jak je máš (včetně sloupce `Sector`) a do formule přidat (`+ C(Sector)`, kde to `C()` znamená, že jde o kategorickou proměnnou). Dokumentace k tomu je [zde](https://www.statsmodels.org/dev/example_formulas.html).
- Když používáš kategorické proměnné v regresi, obvykle se jedna kategorie vyřazuje (v `pd.get_dummies` nastavíš `drop_first=True`). Ta vyřazená kategorie pak slouží jako referenční, tj. ostatní se s ní porovnávají.
- Dokázala bys říct, co znamenají regresní koeficienty, u těch jednotlivých kategorií proměnné `Sector`? Ty co vidíš v summary té regrese?

Formální doporučení:

- Dát do toho notebooku kromě zadání úkolu i trochu větší kontext, o co jde. Třeba se k tomu budeš chtít jednou vrátit nebo to ukázat někomu během pohovoru ;-).
- Nemusíš si vytvářet další data pro korelaci nebo pro modelování (pokud neodmazáváš řádky), všechno to můžeš počítat z jednoho dataframu. Např. můžeš použít `data.corr(numeric_only=True)`, když máš formuli, můžeš si v těch datech, na které voláš fit nebo predict nechat i ostatní sloupce, nevadí to. Bude to pak trochu přehlednější.

Pokud budeš chtít úkol ještě upravovat, dej vědět. Jinak to zavřeme a poznačím to do tabulky.

Díky, V.

**Comment by Verutynka** [comment]
Ahoj,

díky za vyčerpávající zpětnou vazbu. Zkusila bych ještě doupravit tu trojku
a doladit ten zbytek. V té 3 jsem pd.concat zkoušela, ale nějak mě to
zlobilo, tak se na to ještě podívám. Ať to dává smysl, když na to budu
později koukat 🙂 Doufám, že se mi to podaří poslat dnes nebo zítra.
Uvidím, co na to řeknou děti 😅

Zatím moc dík

Verča

ne 19. 11. 2023 v 12:26 odesílatel Václav Čepelák ***@***.***>
napsal:

**Comment by vaclavcepelak** [comment]
Ahoj Veroniko,

děkuju moc za to, že jsi tu zpětnou vazbu vzala tak vážně :). Je vidět, že sis s tím dala práci a je vidět, že to chápeš. Jedna  poznámka k regresním koeficientům u proměnné sektor:

V tomhle případě ta regrese vypočte regresní koeficient pro každou kategorii proměnné `Sector` (kromě první `Basic Materials`, která je pak referenční). Například regresní koeficient `C(Sector)[T.Communication Services] = -3.7782` znamená, že sektor `Communication Services` má proti sektoru `Basic Materials` (= referenční kategorie) hodnotu Y o 3.78 nižší. Přesněji řečeno: budu-li mít 2 stejné firmy se stejnými vlastnostmi a jedna bude ze sektoru `Comunication Services` a druhá z `Basic Materials`, bude ta první mít hodnotu Y v průměru o 3.78 nižší než ta druhá.

Děkuju za vynaložené úsilí a držím palce ve zbytku kurzu.
