### ISSUE TITLE
PythonProDataScience_Ukol2

### ISSUE THREAD

**Issue by Verutynka** [Verutynka/PythonProDataScience_Ukol#2]
Konečně odevzdávám druhý úkol, děkuji za opravení  :-) @vaclavcepelak

**Comment by vaclavcepelak** [comment]
Ahoj Veroniko, povedlo se, úkol je splněn! Funguje to, jak má a cením i přehlednost kódu a komentáře!

Je tam jedna zásadnější věc - chybí ti tam StandardScaler. A zároveň to není chyba, protože v tomhle případě zrovna není potřeba - věděla bys proč? Nechci tě tím už zatěžovat, takže odpověď na otázku nevyžaduji - úkol je splněn. 

V rámci sekce "rady do života" přidávám jednu věc:
- V tom nepovinném úkolu máš jeden zbytečný řádek kódu (reshape) - zbyl tam po Jirkovi, ale ty to děláš už v předchozím kroku. Ale není to chyba.
